[package]
name = "choreo"
version = "0.1.0"
authors = ["Claes Adamsson <claes.adamsson@gmail.com>"]
repository = "https://github.com/cladam/choreo"
readme = "README.md"
license = "MIT"
description = "DSL for BDD type testing."
keywords = ["dsl"]
categories = ["command-line-utilities", "development-tools"]
edition = "2021"

[dependencies]
pest = "2.8.1"
pest_derive = "2.8.1"
predicates = "3.1.3"
strip-ansi-escapes = "0.2.1"
terminal_size = "0.4.3"
thiserror = "2.0.16"
anyhow = "1.0.99"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
toml = "0.9.5"
chrono = { version = "0.4.41", features = ["serde"] }
portable-pty = "0.9.0"

[lib]
name = "choreo"
path = "src/lib.rs"