name: Build, Test, and Release

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Trigger on version tags like v0.1.0
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  # A dummy environment variable for the medi test
  EVAR: "## My medi note from an environment variable"

jobs:
  validate-examples:
    name: Validate Examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Validate all examples
        run: |
          for file in examples/*.chor; do
            echo "Validating $file"
            ./target/release/choreo validate --file "$file"
          done

  build-and-test:
    needs: validate-examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Check cargo formatting
        run: cargo fmt -- --check


      # No unittests for now, the regression tests are more important
      #- name: Run tests
      #  run: cargo test

      - name: Run `advanced matchers` example
        run: ./target/release/choreo run --file examples/advanced_matchers.chor

      - name: Run `checking date` example
        run: ./target/release/choreo run --file examples/checking_date.chor

      - name: Run `checking userid` example
        run: ./target/release/choreo run --file examples/checking_userid.chor

      - name: Run `extracting fields` example
        run: ./target/release/choreo run --file examples/extracting_fields.chor

      - name: Run `fs operations` example
        run: ./target/release/choreo run --file examples/fs_operations.chor

      # Commenting out bc it fails on GH runners due to permission issues
      #- name: Run `git operations` example
      #  run: ./target/release/choreo run --file examples/git_operations.chor

      - name: Run `new terminal conditions` example
        run: ./target/release/choreo run --file examples/new_terminal_conditions.chor

      - name: Run `process timout` example
        run: ./target/release/choreo run --file examples/process_timout.chor

      - name: Run `redirecting output tee` example
        run: ./target/release/choreo run --file examples/redirecting_output_tee.chor

      - name: Run `setting demo` example
        run: ./target/release/choreo run --file examples/setting_demo.chor

      - name: Run `simulate mocking` example
        run: ./target/release/choreo run --file examples/simulate_mocking.chor

      - name: Run `sorting lines` example
        run: ./target/release/choreo run --file examples/sorting_lines.chor

      - name: Run `tar verification` example
        run: ./target/release/choreo run --file examples/tar_verification.chor

      - name: Run `test ls` example
        run: ./target/release/choreo run --file examples/test_ls.chor

      - name: Run `test system interactions` example
        run: ./target/release/choreo run --file examples/test_system_interactions.chor

      - name: Run `translating char` example
        run: ./target/release/choreo run --file examples/translating_char.chor

      - name: Run `variable substitution` example
        run: ./target/release/choreo run --file examples/variable_substitution.chor

      - name: Run `API Health Check` example
        run: ./target/release/choreo run --file examples/health_check.chor

      - name: Run `Web Conditions` example
        run: ./target/release/choreo run --file examples/web_conditions.chor
              
      # These tests require installing medi on the runner
      #- name: Install medi for the next tests
      #  run: cargo install medi

      #- name: Run 'medi' example
      #  run: ./target/release/choreo run --file examples/medi_env_workflow.chor

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/v')
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  # Job 3: Builds binaries for multiple platforms and uploads them. Only runs on new tags.
  build_and_upload_assets:
    name: Build & Upload Release Assets
    needs: create_release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install aarch64 linker (for cross-compiling on Ubuntu)
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build binary
        env:
          # Set linker for aarch64 cross-compile
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Package binary for release
        shell: bash
        run: |
          # The binary will be in the release directory
          cd target/${{ matrix.target }}/release
          
          # Rename the binary to include the target triple
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv choreo.exe choreo-${{ matrix.target }}.exe
            echo "ASSET_NAME=choreo-${{ matrix.target }}.exe" >> $GITHUB_ENV
          else
            mv choreo choreo-${{ matrix.target }}
            echo "ASSET_NAME=choreo-${{ matrix.target }}" >> $GITHUB_ENV
          fi

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./target/${{ matrix.target }}/release/${{ env.ASSET_NAME }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/octet-stream

  # Job 4: Publishes to crates.io. Only runs on new tags.
  publish_to_crates:
    name: Publish to crates.io
    needs: build-and-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }}